//
// C O N S T A N T S
//
// ASX 200 Stock list
export const ASX200STOCKSTEST = ["ALX"];
export const ASX200STOCKS= [
  "360",
  "A2M",
  "AGL",
  "AIA",
  "AKE",
  "ALD",
  "ALL",
  "ALQ",
  "ALU",
  "ALX",
  "AMC",
  "AMP",
  "ANN",
  "ANZ",
  "APA",
  "APE",
  "ARB",
  "ARF",
  "ASX",
  "AUB",
  "AWC",
  "AZJ",
  "BAP",
  "BEN",
  "BGA",
  "BGL",
  "BHP",
  "BKW",
  "BLD",
  "BOE",
  "BOQ",
  "BPT",
  "BRG",
  "BSL",
  "BWP",
  "BXB",
  "CAR",
  "CBA",
  "CCP",
  "CGC",
  "CGF",
  "CHC",
  "CHN",
  "CIA",
  "CIP",
  "CKF",
  "CLW",
  "CMM",
  "CNI",
  "CNU",
  "COH",
  "COL",
  "CPU",
  "CQE",
  "CQR",
  "CRN",
  "CSL",
  "CSR",
  "CTD",
  "CWY",
  "CXO",
  "DEG",
  "DHG",
  "DMP",
  "DOW",
  "DRR",
  "DTL",
  "DXS",
  "EDV",
  "ELD",
  "EMD",
  "EVN",
  "EVT",
  "FBU",
  "FLT",
  "FMG",
  "FPH",
  "GMD",
  "GMG",
  "GNC",
  "GOR",
  "GPT",
  "GUD",
  "HDN",
  "HLI",
  "HLI",
  "HLS",
  "HMC",
  "HUB",
  "HVN",
  "IAG",
  "IEL",
  "IFL",
  "IGO",
  "ILU",
  "INA",
  "ING",
  "IPH",
  "IPL",
  "IRE",
  "JBH",
  "JHX",
  "JLG",
  "KAR",
  "KLS",
  "LIC",
  "LLC",
  "LNW",
  "LOV",
  "LTR",
  "LYC",
  "MFG",
  "MGR",
  "MIN",
  "MND",
  "MP1",
  "MPL",
  "MQG",
  "MTS",
  "NAB",
  "NAN",
  "NEC",
  "NEM",
  "NEU",
  "NHC",
  "NHF",
  "NIC",
  "NSR",
  "NST",
  "NUF",
  "NWH",
  "NWL",
  "NWS",
  "NXT",
  "ORA",
  "ORG",
  "ORI",
  "PDN",
  "PLS",
  "PME",
  "PMV",
  "PNI",
  "PNV",
  "PPT",
  "PRU",
  "PXA",
  "QAN",
  "QBE",
  "QUB",
  "REA",
  "REH",
  "RHC",
  "RIO",
  "RMD",
  "RMS",
  "RRL",
  "RWC",
  "S32",
  "SCG",
  "SCP",
  "SDF",
  "SEK",
  "SFR",
  "SGM",
  "SGP",
  "SGR",
  "SHL",
  "SIQ",
  "SLR",
  "SOL",
  "SPK",
  "SQ2",
  "STO",
  "SUL",
  "SUN",
  "SVW",
  "SYA",
  "TAH",
  "TCL",
  "TLC",
  "TLS",
  "TLX",
  "TNE",
  "TPG",
  "TWE",
  "VCX",
  "VEA",
  "VNT",
  "VUK",
  "WAF",
  "WBC",
  "WBT",
  "WDS",
  "WEB",
  "WES",
  "WHC",
  "WOR",
  "WOW",
  "WPR",
  "WTC",
  "XRO",
];
export const DUPLICATESTOCKS = ["HLI"];

export const priceFields = [
  "symbol",
  "typeDisp",
  "regularMarketPrice",
  "regularMarketDayHigh",
  "regularMarketDayLow",
  "epsCurrentYear",
  "trailingPE",
  "ask",
  "bid",
  "longName",
  "averageAnalystRating",
  "dividendYield",
  "priceGrowth"
];
export const historicFields = ["indicators", "priceGrowthFlag"];

export const hdyFields = [
  "symbol",
  "typeDisp",
  "regularMarketPrice",
  "longName",
  "dividendYield",
];
export const top5stocksFields = [
  "symbol",
  "typeDisp",
  "regularMarketPrice",
  "longName",
  "dividendYield",
  "indicators",
  "priceGrowth"
]; //, "divGrowth"]

// export const ASX200STOCKSOLD =  ["A2M","AAA","ABC","ABG","AFI","AGL","AIA","ALD","ALL","ALQ","ALU","ALX","AMC","AMP","ANN","ANZ","APA","APE","APT","APX","ARB","ARG","AST","ASX","AWC","AZJ","BAP","BEN","BGA","BHP","BIN","BKW","BLD","BOQ","BPT","BRG","BSL","BWP","BXB","CAR","CBA","CCL","CCP","CDA","CGF","CHC","CHN","CIA","CIM","CLW","CMW","CNU","COH","COL","CPU","CQR","CSL","CSR","CTD","CWN","CWY","DEG","DHG","DMP","DOW","DRR","DXS","EBO","ELD","EML","EVN","EVT","FBU","FLT","FMG","FPH","GMG","GNE","GOZ","GPT","GXY","HLS","HVN","IAG","IEL","IFL","IFT","IGO","ILU","IOO","IOZ","IPL","IRE","IVV","JBH","JHX","LFG","LFS","LLC","LNK","LYC","MCY","MEZ","MFG","MGF","MGO","MGR","MIN","MLT","MP1","MPL","MQG","MTS","NAB","NCM","NEC","NHF","NIC","NSR","NST","NUF","NWL","NXT","ORA","ORE","ORG","ORI","OSH","OZL","PBH","PDL","PLS","PME","PMG","PMV","PNI","PNV","PPT","PTM","QAN","QBE","QUB","REA","REH","RHC","RIO","RMD","RRL","RWC","S32","SCG","SCP","SDF","SEK","SGM","SGP","SGR","SHL","SKC","SKI","SLK","SNZ","SOL","SPK","STO","STW","SUL","SUN","SVW","SYD","TAH","TCL","TLS","TLT","TNE","TPG","TWE","TYR","VAP","VAS","VCX","VEA","VEU","VGS","VOC","VTS","VUK","WAM","WBC","WEB","WES","WOR","WOW","WPL","WPR","WTC","XRO","YAL","Z1P","ZIM"];

//
// F U N C T I O N S
//
async function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function compareStrings(a, b) {
  // Assuming you want case-insensitive comparison
  a = a.toLowerCase();
  b = b.toLowerCase();
  return a < b ? -1 : a > b ? 1 : 0;
}

export { sleep, compareStrings };
